"""Nifty 50 + select Nifty 500 stocks for Indian market scanning."""

_NIFTY50 = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "SBIN.NS", "BHARTIARTL.NS", "ITC.NS", "KOTAKBANK.NS",
    "LT.NS", "AXISBANK.NS", "HCLTECH.NS", "ASIANPAINT.NS", "MARUTI.NS",
    "SUNPHARMA.NS", "TITAN.NS", "BAJFINANCE.NS", "DMART.NS", "ULTRACEMCO.NS",
    "NTPC.NS", "WIPRO.NS", "ONGC.NS", "POWERGRID.NS", "M&M.NS",
    "TATAMOTORS.NS", "JSWSTEEL.NS", "TATASTEEL.NS", "ADANIENT.NS", "ADANIPORTS.NS",
    "TECHM.NS", "INDUSINDBK.NS", "HINDALCO.NS", "DRREDDY.NS", "BAJAJFINSV.NS",
    "CIPLA.NS", "NESTLEIND.NS", "DIVISLAB.NS", "BRITANNIA.NS", "APOLLOHOSP.NS",
    "COALINDIA.NS", "GRASIM.NS", "BPCL.NS", "EICHERMOT.NS", "SBILIFE.NS",
    "HDFCLIFE.NS", "HEROMOTOCO.NS", "BAJAJ-AUTO.NS", "TATACONSUM.NS", "SHRIRAMFIN.NS",
]

_NIFTY_MIDCAP_SELECT = [
    "ZOMATO.NS", "PAYTM.NS", "NYKAA.NS", "POLYCAB.NS", "PERSISTENT.NS",
    "TRENT.NS", "PHOENIXLTD.NS", "MPHASIS.NS", "COFORGE.NS", "LTIM.NS",
    "MAXHEALTH.NS", "ASTRAL.NS", "DEEPAKNI.NS", "PIIND.NS", "ATUL.NS",
    "ABCAPITAL.NS", "SUNTV.NS", "FEDERALBNK.NS", "CUMMINSIND.NS", "ESCORTS.NS",
    "VOLTAS.NS", "PAGEIND.NS", "MUTHOOTFIN.NS", "AUBANK.NS", "CROMPTON.NS",
    "IDFCFIRSTB.NS", "JUBLFOOD.NS", "GODREJCP.NS", "OBEROIRLTY.NS", "LALPATHLAB.NS",
]


def get_nifty_tickers(scope: str = "nifty50") -> list[str]:
    if scope == "nifty50":
        return _NIFTY50
    elif scope == "extended":
        return _NIFTY50 + _NIFTY_MIDCAP_SELECT
    return _NIFTY50
